version: '3.8'
services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.13.2
    container_name: elasticsearch
    environment:
      - "ELASTIC_PASSWORD=${ELASTICSEARCH_PASSWORD}"
      - "xpack.security.enabled=true"
      - "xpack.security.authc.api_key.enabled=true"
      - "discovery.type=single-node"
    ports:
      - "9200:9200"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - data:/usr/share/elasticsearch/data
    networks:
      - esnet

  app:
    build: .
    container_name: python_app
    volumes:
      - ./src:/usr/src/app 
    depends_on:
      - elasticsearch
    networks:
      - esnet
    environment:
      - ELASTICSEARCH_USERNAME=${ELASTICSEARCH_USERNAME}
      - ELASTICSEARCH_PASSWORD=${ELASTICSEARCH_PASSWORD}
      - URL=${URL}
    ports:
      - "${PORT:-5000}:5000"
    command: ["flask", "run", "--host=0.0.0.0"]


volumes:
  data:

networks:
  esnet:
